watch_dir: /watch
destination_dir: /destination
error_dir: /watch/errors
video_extensions: [.mp4, .mkv, .avi, .wmv]

api:
  base_url: http://wpfamilyhubid_nginx/wp-json/emby/v1
  token: ""
  search_order: [missav, javguru]

stability:
  check_interval_seconds: 5
  min_stable_checks: 2
